### ISSUE TITLE
Django 1.10 error

### ISSUE THREAD

**Issue by cereigido** [fabiocaccamo/django-admin-interface#5] opened 2016-08-04 01:13 UTC
django.core.exceptions.SuspiciousFileOperation: The joined path ([...]/.virtualenvs/intranet/lib/python2.7/site-packages/admin_interface/data/logo-django.svg) is located outside of the base path component ([...]/media)

**Comment by fabiocaccamo** [comment] 2016-08-04 11:18
Hi @cereigido, 
thanks for the report, I didn't tested yet this lib against Django 1.10.

The problem is that the default logo is attached as logo of the default theme from a 'data' directory of the lib: https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/models.py#L88

I think the only solution is to use it as static file, have you any suggestion?

**Comment by cereigido** [comment] 2016-08-05 04:32
@fabiocaccamo,

Just setting file_name on django.core.files.File did the trick.

I sent a pull request with the fix.

**Comment by fabiocaccamo** [comment] 2016-08-05 08:40
@cereigido 
I just merged your PR, and released 0.1.7 version on pypi.
Thank you.

**Closed by fabiocaccamo** 2016-08-05 08:40 UTC
Labels: bug
