### ISSUE TITLE
Logo & Favicon not rendering

### ISSUE THREAD

**Issue by CharlesFr** [fabiocaccamo/django-admin-interface#310] opened 2023-08-13 12:59 UTC
I've configured everything as it should be but Django cannot find the favicon or logo. What am I missing?

```
# settings.py
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
```

```
# urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

I can see that the files are correctly being stored as expected: `app\media\admin-interface\favicon\favicon.ico`

**Python version**
3.10.12

**Django version**
4.2.4

**Package version**
0.26.0

**Current behavior (bug description)**
```
[DJANGO] WARNING 2023-08-13 12:52:56,660 log django.request.log_response:241: Not Found: /media/admin-interface/favicon/favicon.ico
[DJANGO] WARNING 2023-08-13 12:53:26,440 log django.request.log_response:241: Not Found: /media/admin-interface/logo/Logo_kyvHNK9.png
```

**Expected behavior**
I'm expecting the favicon and logo to render in the admin GUI.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/310">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/310/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/310/pledge.svg">
</picture>
</a>

**Comment by CharlesFr** [comment] 2023-08-13 16:14
@fabiocaccamo mind providing details on invalidity?

**Comment by fabiocaccamo** [comment] 2023-08-13 17:00
@CharlesFr probably a duplicate of #86 or #261

**Comment by CharlesFr** [comment] 2023-08-13 17:08
I see, I've been through both and implement all suggestions without luck.

**Comment by fabiocaccamo** [comment] 2023-08-13 19:38
Have you run `python manage.py collectstatic`?

**Comment by CharlesFr** [comment] 2023-08-14 08:39
Yeah, I have tried multiple time. 

I'm running the Django app inside a Docker container - could this have something to do with it?

**Comment by CharlesFr** [comment] 2023-08-14 11:23
The installation doesn't mention anything about `MEDIA_ROOT` or `MEDIA_URL`, should I omit these from my `settings.py`?

**Comment by fabiocaccamo** [comment] 2023-08-14 16:36
They are not mentioned because are standard django settings that must always be configured correctly to use media and static files.

**Comment by fabiocaccamo** [comment] 2023-08-24 16:30
@CharlesFr please let us know if you managed to solve this issue with the help of @FraCata00

**Comment by CharlesFr** [comment] 2023-08-24 16:46
@FraCata00 I'm assuming I've done this right since if I open a terminal session inside the `web` container then logo files are there:

```
root@de90af83604d:/app# cd media/
root@de90af83604d:/app/media# ls
admin-interface
root@de90af83604d:/app/media# cd admin-interface/
root@de90af83604d:/app/media/admin-interface# ls
favicon  logo
root@de90af83604d:/app/media/admin-interface# cd logo
root@de90af83604d:/app/media/admin-interface/logo# ls
Logo.png
root@de90af83604d:/app/media/admin-interface/logo# 
```

However django is still not able to find them:

```
[DJANGO] WARNING 2023-08-24 16:41:37,569 log django.request.log_response:241: Not Found: /media/admin-interface/logo/Logo.png
[DJANGO] WARNING 2023-08-24 16:41:37,571 basehttp django.server.log_message:212: "GET /media/admin-interface/logo/Logo.png HTTP/1.1" 404 7934
```

**Comment by FraCata00** [comment] 2023-08-24 16:52
@CharlesFr Mmh okay, so each nginx container must be able to find the media file

**Comment by CharlesFr** [comment] 2023-08-24 17:02
I'm currently testing locally, and the application consists of 6 containers (celery, redis...) defined in a docker-compose.yaml.

Currently the web server is being started simply like this: `python manage.py runserver 0.0.0.0:8000`

I have not defined nginx conf anywhere.

**Comment by FraCata00** [comment] 2023-08-24 17:12
Okay because in development is Django that serve the static files 
So, in the settings of admin interface, inside the change view of theme, there is a path under the Logo field like link path
If you click that link, view the correct logo or http 404 exception?

**Comment by CharlesFr** [comment] 2023-08-24 18:29
Yes, I get 404:

![Screenshot 2023-08-24 192520](https://github.com/fabiocaccamo/django-admin-interface/assets/16102087/f424d4c0-7f11-4cb6-a7d0-485c6578d292)

**Comment by CharlesFr** [comment] 2023-08-24 19:10
Here it is:

```
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

**Comment by FraCata00** [comment] 2023-08-24 19:14
Try to change the settings url exactly with my example and not with `os.path.join`

Absolutely is correct but force the named url with only string like my example, not autoresolve with os library

**Closed** 2023-08-28 20:26 UTC
Labels: invalid
