### ISSUE TITLE
Fiedsets as tabs CSS issue

### ISSUE THREAD

**Issue by bloodwithmilk25** [fabiocaccamo/django-admin-interface#317] opened 2023-09-06 16:04 UTC
Python
3.11
Django
4.2.2
django-admin-interface
0.26.0

When the "Fieldsets as tabs" feature is enabled, the help text CSS does not look right. 
Should it look like this or is it a bug? We don't have any custom CSS.
It looks like it's related to the Django version we are using. On my other project, I have Django 4.1.9 and CSS is fine. When I updated Django on that other project, the issue appeared there too.

<img width="776" alt="Screenshot 2023-09-06 at 18 57 04" src="https://github.com/fabiocaccamo/django-admin-interface/assets/37488321/3913fc6e-7918-4958-b0cb-000440bbd0c9">
<img width="557" alt="Screenshot 2023-09-06 at 18 53 48" src="https://github.com/fabiocaccamo/django-admin-interface/assets/37488321/e54f772c-025d-404d-86a5-2d1312e8748f">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-admin-interface/issues/317">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/317/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/317/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment] 2023-09-06 16:13
@bloodwithmilk25 thank you for reporting this.

> Should it look like this or is it a bug?

It's a CSS bug

**Comment by bloodwithmilk25** [comment] 2023-09-06 16:45
@fabiocaccamo No, it looks just fine without this option

**Comment by fabiocaccamo** [comment] 2023-09-18 19:33
@bloodwithmilk25 I checked the cause of this problem and:

- the good news is that it seems that *finally* the `help_text` is left-aligned with the inputs independently by the left margin.

- the bad news is that fixing this issue now, would result in breaking the layout for all users that are not using the latest `django` version.

Patching the CSS only for the latest version would work, but it would also implies some additional maintenance work in the future and I don't want to do it.

So in the end I would opt for having the best compatibility with the latest/coming django versions, users can avoid to upgrade this library to avoid unexpected misalignments.

**Comment by bloodwithmilk25** [comment] 2023-09-19 08:15
@fabiocaccamo I think you are right. It's not a big deal since it's only happening on django 4.2 and with a "Fieldsets as tabs" enabled, so I don't think many users are affected. We can return to it later when more users use Django >=4.2.

Would you mind posting a patched section of the CSS? I'll patch it just in my project

**Comment by fabiocaccamo** [comment] 2024-01-08 22:30
@bloodwithmilk25 this has been fixed in `0.28.3` version, please let me know if you notice any other problem.

**Closed by fabiocaccamo** 2024-01-08 22:30 UTC
Labels: bug

**Comment by bloodwithmilk25** [comment] 2024-01-19 10:45
@fabiocaccamo Thank you very much
