### ISSUE TITLE
Collapsable Filter Menu

### ISSUE THREAD

**Issue by smunoz-ml** [fabiocaccamo/django-admin-interface#163] opened 2022-06-01 19:16 UTC
Hi!

Would it be possible to add a button to hide the filters the same way the left menu is hidden? I have faced situations where the users won't use the filters on a daily basis and, in small screens, the filters fill an important piece of screen and they have to scroll horizontally to view the data in the list.

Thank you for this amazing interface! 🙌🏻

**Comment by fabiocaccamo** [comment] 2022-06-02 14:15
@smunoz-ml interesting feature!

**Comment by rikengct** [comment] 2022-07-13 03:43
i too have longed for this option for the same reasons. would be VERY useful.

**Comment by fabiocaccamo** [comment] 2023-05-11 08:38
@smunoz-ml I close this because it's a duplicate of #252, in reality #252 is a duplicate of this, but I noticed it too late *(sorry)* and there are more info on the other issue, so I prefer to keep the other one open.

**Closed by fabiocaccamo** 2023-05-11 08:38 UTC
Labels: enhancement
