### ISSUE TITLE
CSS as FileField in `Theme` model

### ISSUE THREAD

**Issue by asiffer** [fabiocaccamo/django-admin-interface#138] opened 2021-11-16 14:11 UTC
Hello,

I have seen that the `Theme` model allow to "inject" raw css through its `css` attribute. However it is a TextField and it is not so easy to use in practice (for instance we need to inline the css code in the json fixture). I think it could be great to either turn this field into a FileField or to add a new FileField attribute like `css_file`. Of course I can help through a PR :)

**Comment by merwok** [comment] 2021-11-16 17:47
Would a textarea field work for you?  A file field is a bit heavy in my opinion.

**Comment by asiffer** [comment] 2021-11-17 07:58
Thank you for your reply!
I would prefer a file because it allows to easily add an css stylesheet in Theme. Obviously, It would play the same role as `css` attribute but the workflow would be a bit better: to maintain or update the Theme, I would merely have to edit a static css stylesheet rather than inlining all the css code. I do agree that it is a bit heavy but the counterpart is that we don't need to think about both the amount of css code we add and the way we add it. For example, the logo and favicon are files and we do not imagine to store them as inlined bytes.
A textarea would be nice to edit in the admin site but I think more in terms of fixtures.

**Comment by merwok** [comment] 2021-11-17 15:28
Could you clarify if you’re talking about a CSS _media_ file (added with a file field in the admin) or a _static_ file (present in your source)?  Static file is already possible (I use that!), is easy to edit and is version controlled.  A media file does not seem so practical to me (you have to download it to view it, can’t see changes easily).

**Comment by asiffer** [comment] 2021-11-17 15:43
Oh I probably missed it! How do you use static file?

**Comment by merwok** [comment] 2021-11-17 18:07
For example, I have overriden the `admin/change_form.html` template to add custom behaviour and style for object edit pages with inline JavaScript and CSS.  I could move the CSS to its own file and use `<link rel="stylesheet" href="{% static "example_custom/extras.css" %}">`.

**Comment by asiffer** [comment] 2021-11-18 08:05
Ok, I understand but it means that I have to modify the templates you have developed. Of course I can, but I would prefer to do it through the project "API" (I mean the `Theme` model) and not by editing some code I am not really supposed to modify.
I merely want to make this feature available through the API. If you think that your way to do it is enough, I won't insist :)

**Comment by merwok** [comment] 2021-11-18 17:51
Overriding templates is definitely supported by django and not wrong or unclean.
It works for me, but I also understand the request for something that can be done through the admin, without changing files, and with different contents for each theme!  Let’s see what the project maintainer thinks :)

**Comment by fabiocaccamo** [comment] 2021-11-18 23:40
I agree with @merwok, and I would like to add also that it is possible to do it (per model) also using the ModelAdmin:
https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#modeladmin-asset-definitions

@asiffer I understand your need, maybe that 2 fields could be added (`extra_asset_css` and `extra_asset_js`) to cover also these situations, then developers are free to decide which solution fits better with their needs. Anyway if your css modifications are not too specific to your case and could be useful to others you could suggest them here.

**Comment by fabiocaccamo** [comment] 2021-11-23 21:36
@asiffer I keep this issue open, but at the moment it is not my intention to add support to custom css/js files. 

As said, if you have some changes/improvements to purpose they are welcome.

**Comment by asiffer** [comment] 2021-11-24 07:58
Ok thank you @fabiocaccamo, I think I will propose un PR

**Comment by fabiocaccamo** [comment] 2021-11-24 09:12
@asiffer the point is that I'm always more convinced that `custom_css` and `custom_js` fields would have more cons than pro and could become kind of black-box of problems very hard to debug. Imagine this scenario: for any reported bug I should ask if there is some custom css / js and if yes I should check if the bug is caused by those files or not, a real maintenance nightmare. 

@merwok what do you think about it?

**Comment by asiffer** [comment] 2021-11-24 09:30
Currently, `Theme` has a `css` TextField where you can put raw css. My initial wish would be to make it a FileField like `favicon` or `logo` attributes (I am not initially interested in js but maybe some people could have this need). Maybe we can define a CSSFileField with a custom `value_to_string` that will inline the css code in the fixture. In your scenario, you will then have the same output as today.

**Comment by fabiocaccamo** [comment] 2021-11-24 09:35
The `css` field is very old and I decided to remove it for the same reasons. I only hidden it in the admin but not removed it from the model for backward-compatibility, but I'm going to definitively remove it for the next release.

**Comment by asiffer** [comment] 2021-11-24 09:38
Ok so I understand that the feature goes against the spirit of your package. We can probably close the issue.

**Comment by fabiocaccamo** [comment] 2021-11-24 10:11
Yes, probably it is better to close it.

**Closed by fabiocaccamo** 2021-11-24 10:11 UTC
Labels: enhancement, wontfix
