### ISSUE TITLE
Cache admin settings

### ISSUE THREAD

**Issue by cmc333333** [fabiocaccamo/django-admin-interface#19] opened 2017-06-08 20:48 UTC
Each call to `Theme.get_active_theme` makes multiple database calls. Unfortunately, that's called in the `get_admin_interface_theme` template tag, which appears multiple times on each admin page render.

We should cache these calls at least per request to speed up performance.

**Comment by fabiocaccamo** [comment] 2017-06-09 08:29
You're right, thanks for the issue, I will fix it (per-request cache) as soon as possible.

**Comment by fabiocaccamo** [comment] 2017-06-09 10:24
You can upgrade to `0.4.6` version :)

**Comment by cmc333333** [comment] 2017-06-09 13:11
Nice solution!

**Comment by fabiocaccamo** [comment] 2017-06-09 13:25
Thanks!

**Comment by dionysio** [comment] 2017-08-16 15:25
hey @fabiocaccamo. I'm still seeing too many db calls even after the fix. I'm on version 0.5.1 with django 1.11.4. Can you look into it?

Here's a screenshot from debug toolbar: https://snag.gy/SI3ZO8.jpg

**Comment by fabiocaccamo** [comment] 2017-08-16 21:33
It's really strange, as you can see in the template tags file, the theme is stored as a request attribute. I will write a test for it, or if you can do it, it would be appreciated.

**Comment by fabiocaccamo** [comment] 2017-08-24 12:34
@dionysio duplicated queries was caused by the get_active_theme method and not by the template tag, by the way it has been fixed and you can upgrade to `0.5.2` version (don't forget to run migrations when upgrading).

**Comment by fabiocaccamo** [comment] 2017-09-07 15:42
Multiple database calls if list_filter is present.

**Comment by fabiocaccamo** [comment] 2017-09-25 08:31
I investigated the problem and I discovered that the `admin_interface_theme` variable stored as request attribute in the template-tag doesn't persist if the template-tag is used in another template (in this case the `filter.html` template).

A solution could be to cache the value for 1 second to guarantee 1 query for each request.
@dionysio @cmc333333 what do you think about it?

**Comment by fabiocaccamo** [comment] 2017-10-02 08:29
@dionysio @cmc333333 if you don't partecipate actively to this issue I will close it.

**Comment by cmc333333** [comment] 2017-10-02 13:46
I think a one-second cache is a bit inelegant. Perhaps a better long-term strategy would be to cache the value for days and clear that cache when the value changes? Using Django's [signals](https://docs.djangoproject.com/en/1.11/topics/signals/) would be a good strategy here. Using Django's [cache framework](https://docs.djangoproject.com/en/1.11/topics/cache/) would also allow users to swap out the implementation and configure the amount of time before expiry.

**Comment by fabiocaccamo** [comment] 2019-03-21 09:36
@merwok do you know the cause of multiple database calls (actually 2) if `list_filter` is present?

I could easily fix this issue adding a `context processor`, but I would keep the zero-config setup too.

**Comment by merwok** [comment] 2019-03-21 13:43
list_filter where?  Do you have a code example?


About caching: django cache + signal to invalidate seems good.  In general, I like to implement caching in the manager, which is the interface between the code and the database.
  
(To follow django’s way, Theme.get_active_theme / set_active should be Theme.objects.get_active / set_active.  Saving one model instance should change one database record; working with multiple rows is done with manager methods.  I’d like to make that change when I find some time!)

Another piece: instead of inlining the whole CSS in the HTML, a template tag could generate a link to a custom view that serves the CSS with HTTP caching headers.  The caching could be long if the link changes when the model changes (e.g. the link is `/admin/something/styles.{hash(theme.id+theme.updated)}.css`).

**Comment by fabiocaccamo** [comment] 2019-03-21 13:56
If the active theme has `list_filter_dropdown` enabled, a custom `dropdown_filter.html` template [is included in the filter template](https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/templates/admin/filter.html#L7) and two queries are made to retrieve the active theme instead of just one.
You can check it quickly using the debug-toolbar.

About caching: I agree with the manager solution.

About static methods naming: I named them with the "_theme" to avoid confusion with the `active` field, but your suggestion is correct and I'm open to rename it.

About custom view: I agree, it is in the todo since long time :)

**Comment by merwok** [comment] 2019-03-21 15:22
I don’t understand why including the admin_interface/dropdown_filter.html template causes a second DB request!

(My point was not about the naming of the static/class method, but about having them as method on a custom ThemeManager rather than the Theme model class.)

**Comment by fabiocaccamo** [comment] 2019-03-21 15:34
Yes, that's a really strange behavior.
That's ok, I misunderstood.

**Closed** 2019-04-29 15:37 UTC
Labels: enhancement

**Comment by fabiocaccamo** [comment] 2019-04-29 16:49
Fixed in `0.10.4`
