### ISSUE TITLE
Wasted space when not using sidebar

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#105] opened 2020-12-11 00:00 UTC
**Package version**
0.14.1

**Current behavior (bug description)**
Pages don’t use the full width of the screen because of this rule:

```css
@media (min-width:1280px) {
    .admin-interface.change-list:not(.popup) #main.shifted > .content,
    .admin-interface.change-form:not(.popup) #main.shifted > .content {
        max-width: calc(100% - 360px);
    }
}
```

**Expected behavior**

When `admin.site.enable_nav_sidebar` is false, don’t reserve 360px.

**Comment by fabiocaccamo** [comment] 2020-12-15 15:07
@merwok on which django version are you experiencing this problem?
`#main.shifted` selector means that there is sidebar and it is open.

**Comment by JJMeijer** [comment] 2020-12-15 15:34
@fabiocaccamo I also experienced this issue with Django 3.1.4. It's maybe more of a Django issue because they leave the default `.shifted` class in the template even when the sidebar is disabled by setting  `admin.site.enable_nav_sidebar` to false.

**Comment by merwok** [comment] 2020-12-15 15:38
django 3.1.4 too!

**Comment by fabiocaccamo** [comment] 2020-12-15 15:45
@merwok and @JJMeijer do you confirm me that the problem is related to the `admin.site.enable_nav_sidebar = False` setting?

**Comment by merwok** [comment] 2020-12-15 16:46
I wouldn’t put it that way.

It’s more that setting that attribute to false conveys that I don’t want the sidebar*, and the space being reserved nonetheless was a waste (especially on one list page where I needed to show many fields per record and wanted to avoid multiple lines per cell).


* (btw I don’t want the sidebar that because it messed up the login page a lot, so I didn’t even check if I liked it on the regular admin pages)

**Comment by fabiocaccamo** [comment] 2020-12-15 17:11
My idea is that if the admin sidebar setting is false, a body class could be added and the css selector can be modified to work only if that body-class is not present.

**Comment by merwok** [comment] 2020-12-15 18:36
That sounds great for me!

I wonder if it would be unwanted for other people; not everyone used the default global AdminSite instance at `django.contrib.admin.site`.  I would be happy if I had to go and check a setting in the Theme admin page.

**Comment by fabiocaccamo** [comment] 2020-12-16 09:05
@merwok I suppose that if someone is using this package, he is using `django.contrib.admin.site` or do you mean something else?

**Comment by merwok** [comment] 2020-12-16 14:54
Well not necessarily, you can create your own instances of the AdminSite class, not all cases use the default global instance.

**Comment by morlandi** [comment] 2020-12-29 09:00
In my case, I completely removed the "new" left menu from the admin index, since grouping Models by app doesn't fit my needs:

file "url.py":

    from django.contrib import admin
    admin.site.enable_nav_sidebar = False

I confirm the problem described by @merwok, with Django 3.1.4

![1](https://user-images.githubusercontent.com/299854/103272164-6c9f7180-49bc-11eb-928d-f175f7a1801c.png)

When removing django-admin-interface, screen space is recovered:

![2](https://user-images.githubusercontent.com/299854/103272252-a7a1a500-49bc-11eb-826d-d7020d6e6c87.png)

Thank you @fabiocaccamo for a great project ;)

**Comment by fabiocaccamo** [comment] 2021-01-04 12:58
@merwok and @morlandi - this should have been fixed with `0.14.2` version, could you check it?

**Closed** 2021-01-04 12:59 UTC
Labels: bug

**Comment by merwok** [comment] 2021-01-04 15:29
It works!  Thank you 👍🏽

**Comment by morlandi** [comment] 2021-01-04 16:55
Thank you @fabiocaccamo :clap:
It works ! :sunglasses:
